name: Deploy DEV to GCP

on:
  workflow_dispatch: # Manual trigger button

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy DEV folder to GCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dev/**"  # Use ** to get all subfolders and files
          target: "/home/${{ secrets.SSH_USERNAME }}/gitdev"
          strip_components: 1 # This puts the content of dev/ directly into gitdev/
